baseURL = 'http://elijahtate.info'
languageCode = 'en-us'
title = "blog"
theme = "paper"
copyright = "©2026, Elijah Tate"
color = "gray"

[params]
monoDarkIcon = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true